project_id = "heismaqehgqxcrndtqmz"

[functions.generate-monthly-statements]
verify_jwt = false

[functions.generate-statement]
verify_jwt = false

[functions.generate-statement-pdf]
verify_jwt = false

[functions.calculate-late-fee]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.create-rent-payment]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.get-stripe-login-link]
verify_jwt = false

[functions.send-tenant-invite]
verify_jwt = false

[functions.confirm-tenant-account]
verify_jwt = false

[functions.get-invite-details]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-tenant-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.serve-lease-pdf]
verify_jwt = false
