// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Always log the URL for debugging (even if undefined)
console.log('[SUPABASE-CONFIG] Environment check:', {
  SUPABASE_URL: SUPABASE_URL || 'NOT SET',
  hasPublishableKey: !!SUPABASE_PUBLISHABLE_KEY,
  urlLength: SUPABASE_URL?.length || 0,
  urlEndsWith: SUPABASE_URL?.slice(-10) || 'N/A'
});

// Validate environment variables
if (!SUPABASE_URL) {
  console.error(
    '❌ VITE_SUPABASE_URL is not set!\n' +
    'Please set VITE_SUPABASE_URL in your environment variables.\n' +
    'For production, set it in your hosting platform (Vercel, Netlify, etc.) and rebuild.'
  );
} else {
  // Check if it looks like a hash/ID instead of a URL
  if (!SUPABASE_URL.startsWith('http://') && !SUPABASE_URL.startsWith('https://')) {
    console.error(
      '❌ INVALID SUPABASE URL FORMAT!\n' +
      `Current value: ${SUPABASE_URL.substring(0, 50)}...\n` +
      'This looks like a project ID or hash, not a full URL!\n\n' +
      'VITE_SUPABASE_URL must be a complete URL, not just an ID.\n' +
      'Correct format: https://<project-id>.supabase.co\n' +
      'Example: https://heismaqehgqxcrndtqmz.supabase.co\n\n' +
      'To find your Supabase URL:\n' +
      '1. Go to your Supabase Dashboard\n' +
      '2. Select your project\n' +
      '3. Go to Settings → API\n' +
      '4. Copy the "Project URL" (not the Project ID)\n' +
      '5. Set that full URL as VITE_SUPABASE_URL in Vercel\n' +
      '6. Redeploy your site'
    );
  }
  // Check for common URL issues
  else if (SUPABASE_URL.includes('.supabase.c') && !SUPABASE_URL.includes('.supabase.co')) {
    console.error(
      '❌ INVALID SUPABASE URL DETECTED!\n' +
      `Current URL: ${SUPABASE_URL}\n` +
      'The URL is missing ".co" - it should end with ".supabase.co" not ".supabase.c"\n\n' +
      '⚠️ IMPORTANT: Vite environment variables are embedded at BUILD TIME!\n' +
      'If you just updated VITE_SUPABASE_URL in your hosting platform:\n' +
      '1. Verify the value ends with ".supabase.co" (not ".supabase.c")\n' +
      '2. You MUST trigger a new BUILD/DEPLOYMENT for the change to take effect\n' +
      '3. Just saving the env var is NOT enough - the site needs to be rebuilt\n\n' +
      'Expected format: https://heismaqehgqxcrndtqmz.supabase.co'
    );
  } else if (SUPABASE_URL.endsWith('.supabase.co')) {
    console.log(`✅ Supabase URL configured correctly: ${SUPABASE_URL}`);
  } else {
    console.warn(`⚠️ Supabase URL format may be incorrect: ${SUPABASE_URL}`);
  }
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set!\n' +
    'Please set VITE_SUPABASE_PUBLISHABLE_KEY in your environment variables.\n' +
    'For production, set it in your hosting platform (Vercel, Netlify, etc.) and rebuild.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co', 
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);