// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Always log the URL for debugging (even if undefined)
console.log('[SUPABASE-CONFIG] Environment check:', {
  SUPABASE_URL: SUPABASE_URL || 'NOT SET',
  hasPublishableKey: !!SUPABASE_PUBLISHABLE_KEY,
  urlLength: SUPABASE_URL?.length || 0,
  urlEndsWith: SUPABASE_URL?.slice(-10) || 'N/A'
});

// Validate environment variables
if (!SUPABASE_URL) {
  console.error(
    '❌ VITE_SUPABASE_URL is not set!\n' +
    'Please set VITE_SUPABASE_URL in your environment variables.\n' +
    'For production, set it in your hosting platform (Vercel, Netlify, etc.) and rebuild.'
  );
} else {
  // Check for common URL issues
  if (SUPABASE_URL.includes('.supabase.c') && !SUPABASE_URL.includes('.supabase.co')) {
    console.error(
      '❌ INVALID SUPABASE URL DETECTED!\n' +
      `Current URL: ${SUPABASE_URL}\n` +
      'The URL is missing ".co" - it should end with ".supabase.co" not ".supabase.c"\n' +
      'Fix this in your hosting platform environment variables and REDEPLOY the site.\n' +
      'Expected format: https://heismaqehgqxcrndtqmz.supabase.co'
    );
  } else if (SUPABASE_URL.endsWith('.supabase.co')) {
    console.log(`✅ Supabase URL configured correctly: ${SUPABASE_URL}`);
  } else {
    console.warn(`⚠️ Supabase URL format may be incorrect: ${SUPABASE_URL}`);
  }
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set!\n' +
    'Please set VITE_SUPABASE_PUBLISHABLE_KEY in your environment variables.\n' +
    'For production, set it in your hosting platform (Vercel, Netlify, etc.) and rebuild.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co', 
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);